from collections.abc import Sequence

class GPUShader:
    def bind(self) -> None: ...
    def uniform_bool(self, name: str, value: bool | Sequence[bool]) -> None: ...
    def uniform_float(self, name: str, value: float | Sequence[float]) -> None: ...
    def uniform_int(self, name: str, value: int | Sequence[int]) -> None: ...

class GPUBatch:
    def draw(self, program: GPUShader | None = None) -> None: ...
