class ed:
    def undo_push() -> None: ...

class mesh:
    def select_all(*, action: str = "TOGGLE") -> None: ...

class object:
    def mode_set(*, mode: str = "OBJECT", toggle: bool = False) -> None: ...

class wm:
    def redraw_timer(type: str, iterations: int) -> None: ...
    def save_userpref() -> None: ...

class skybrush:
    def fix_constraint_ordering() -> None: ...
    def prepare() -> None: ...
    def recalculate_transitions(scope: str) -> None: ...
    def refresh_file_formats() -> None: ...
    def run_all_migrations(*args, **kwargs) -> None: ...
