class ed:
    def undo_push() -> None: ...

class mesh:
    def select_all(*, action: str = "TOGGLE") -> None: ...

class object:
    def mode_set(*, mode: str = "OBJECT", toggle: bool = False) -> None: ...

class wm:
    def open_mainfile(*, filepath: str, use_scripts: bool = True) -> set[str]: ...
    def save_as_mainfile(
        *,
        filepath: str,
        copy: bool = False,
        relative_remap: bool = True,
        check_existing: bool = True,
        compress: bool = False,
    ) -> set[str]: ...
    def redraw_timer(type: str, iterations: int) -> None: ...
    def save_userpref() -> None: ...

class skybrush:
    def fix_constraint_ordering() -> None: ...
    def prepare() -> None: ...
    def recalculate_transitions(scope: str) -> None: ...
    def refresh_file_formats() -> None: ...
    def run_all_migrations(*args, **kwargs) -> None: ...
    def update_time_markers_from_storyboard() -> None: ...
