from pathlib import Path
from typing import Union

def abspath(path: Union[str, Path], *, start: str | bytes | None = None) -> str: ...
def basename(path: Union[str, Path]) -> str: ...
def ensure_ext(filepath: str, ext: str, *, case_sensitive: bool = False) -> str: ...
