from pathlib import Path

def abspath(path: str | Path, *, start: str | bytes | None = None) -> str: ...
def basename(path: str | Path) -> str: ...
def ensure_ext(filepath: str, ext: str, *, case_sensitive: bool = False) -> str: ...
