from typing import Any, Type, TypeAlias, TypeVar

from bpy.types import bpy_prop_collection_idprop

_T = TypeVar("_T")
_PT = TypeVar("_PT")

_PropertyDeferred: TypeAlias = tuple

def BoolProperty(**kwargs: Any) -> bool: ...
def CollectionProperty(
    type: Type[_T], **kwargs: Any
) -> bpy_prop_collection_idprop[_T]: ...
def EnumProperty(**kwargs: Any) -> str: ...
def FloatProperty(**kwargs: Any) -> float: ...
def FloatVectorProperty(**kwargs: Any) -> tuple[float]: ...
def IntProperty(**kwargs: Any) -> int: ...
def PointerProperty(**kwargs: Any) -> _PT: ...
def StringProperty(**kwargs: Any) -> str: ...
