from typing import Any, TypeAlias, TypeVar

_T = TypeVar("_T")
_PT = TypeVar("_PT")

_PropertyDeferred: TypeAlias = tuple

def BoolProperty(**kwargs: Any) -> bool: ...
def CollectionProperty(**kwargs: Any) -> _PT: ...
def EnumProperty(**kwargs: Any) -> str: ...
def FloatProperty(**kwargs: Any) -> float: ...
def FloatVectorProperty(**kwargs: Any) -> tuple[float]: ...
def IntProperty(**kwargs: Any) -> int: ...
def PointerProperty(**kwargs: Any) -> _PT: ...
def StringProperty(**kwargs: Any) -> str: ...
