[project]
name = "dronetara-studio-for-blender"
version = "5.0.3"
description = "Dronetara Studio is a professional drone show designer integrated into Blender"
license = "GPL-3.0-or-later"
authors = [{ name = "Dronetara" }]
maintainers = [{ name = "Dronetara" }]
package-mode = false
requires-python = ">=3.11"
dependencies = ["natsort>=8.0.0"]

[project.urls]
Homepage = "https://github.com/DRONETARA/studio-blender"
Repository = "https://github.com/DRONETARA/studio-blender"
Documentation = "https://github.com/DRONETARA/studio-blender#readme"

[dependency-groups]
dev = [
    "coverage[toml]>=7.15.1",
    "numpy",
    "poethepoet>=0.42.1",
    "pyclean>=2.0.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.5",
    "ty>=0.0.21",
]

[tool.poe.tasks]

format = "ruff format . --check"
format-fix = "ruff format ."

lint = "ruff check ."
lint-fix = "ruff check . --fix"

ty = "ty check src/"

check.sequence = ["format", "lint"]
check.ignore_fail = "return_non_zero"

test.cmd = "python -m pytest test"

[tool.uv.build-backend]
module-root = "src/modules"
module-name = "sbstudio"

[tool.ruff]
lint.ignore = ["B027", "B905", "C901", "E402", "E501", "E731"]
lint.select = ["B", "C", "E", "F", "I", "W"]
extend-exclude = [
  "src/modules/sbstudio/vendor",
  "src/modules/sbstudio/i18n/translations.py",
]

[tool.ty.environment]
extra-paths = ["./typings"]

[tool.ty.src]
exclude = [
  "vendor",
  "src/modules/sbstudio/vendor",
  "src/addons/io_import_dronetara_*.py",
]

[build-system]
requires = ["uv_build>=0.11,<0.12"]
build-backend = "uv_build"
