FontID = int

ROTATION: int
CLIPPING: int
SHADOW: int
KERNING_DEFAULT: int

def color(fontid: FontID, r: float, g: float, b: float, a: float) -> None: ...
def disable(fontid: FontID, option: int) -> None: ...
def draw(fontid: FontID, text: str) -> None: ...
def enable(fontid: FontID, option: int) -> None: ...
def position(fontid: FontID, x: float, y: float, z: float) -> None: ...
def size(fontid: FontID, size: float, dpi: float | None = None) -> None: ...
