from collections.abc import MutableSequence, Sequence
from typing import Literal, TypeAlias

RotationOrder: TypeAlias = Literal["XYZ", "XZY", "YXZ", "YZX", "ZXY", "ZYX"]

class Euler(MutableSequence[float]):
    def __init__(self, angles: tuple[float, float, float], order: RotationOrder, /): ...

class Matrix:
    @classmethod
    def Identity(cls, size: int): ...
    @classmethod
    def Rotation(cls, angle: float, size: int, axis: str | Vector): ...
    @classmethod
    def Translation(cls, vector: Vector): ...
    def __init__(self, rows: Sequence[Sequence[float]] = ()): ...
    @property
    def translation(self) -> Vector: ...
    def to_quaternion(self) -> Quaternion: ...
    def to_euler(
        self, order: RotationOrder = "XYZ", euler_compat: Euler | None = None
    ) -> Euler: ...

class Quaternion(MutableSequence[float]):
    def __init__(self, values: Sequence[float]): ...
    @property
    def w(self) -> float: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...

class Vector(MutableSequence[float]):
    def __init__(self, seq: Sequence[float]): ...
    @property
    def w(self) -> float: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
