from typing import Sequence, Union

class Matrix:
    @classmethod
    def Identity(cls, size: int): ...
    @classmethod
    def Rotation(cls, angle: float, size: int, axis: Union[str, Vector]): ...
    @classmethod
    def Translation(cls, vector: Vector): ...
    def __init__(self, rows: Sequence[Sequence[float]] = ()): ...

class Vector:
    def __init__(self, coords: Sequence[float]): ...
