#!/usr/bin/env python3
"""Script to read `translations_tuple` from `src/modules/sbstudio/i18n/translations.py`
and write a sorted version to `src/modules/sbstudio/i18n/translations_sorted.py`.

Suggested workflow:

    1. Run `python etc/scripts/sort_translations.py`
    2. Overwrite `translations_tuple` in `src/modules/sbstudio/i18n/translations.py`
       with the one in `src/modules/sbstudio/i18n/translations_sorted.py`
    3. Run `ruff format src/modules/sbstudio/i18n/translations.py`
    4. Remove `src/modules/sbstudio/i18n/translations_sorted.py`

"""

import sys
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path

src = (
    Path(__file__).parents[2]
    / "src"
    / "modules"
    / "sbstudio"
    / "i18n"
    / "translations.py"
)
dst = src.parent / "translations_sorted.py"


def main() -> int:

    if not src.exists():
        print(f"Error: Source file not found: {src}", file=sys.stderr)
        return 1

    spec = spec_from_file_location("translations", src)
    module = module_from_spec(spec)
    spec.loader.exec_module(module)

    translations_tuple = tuple(sorted(getattr(module, "translations_tuple", ())))

    with open(dst, "w", encoding="utf-8") as f:
        f.write("# Auto-sorted version of translations_tuple\n")
        f.write("# This file is generated by etc/scripts/sort_translations.py\n\n")
        f.write(f"translations_tuple = {translations_tuple!r}\n")

    print(f"Wrote sorted translations to: {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
