= Overview
:imagesdir: ../assets/images

// Note that this page is very similar (but not identical to) the same pages in the
// Skybrush Live, Skybrush Server, Skybrush firmware and Skybrush Sidekick documentations.
// Synchronous update is recommended in all repos.

*Dronetara Studio* is a Blender-based drone show design application derived from the open-source Skybrush Studio codebase. It remains compatible with parts of the https://skybrush.io/[*Skybrush*] ecosystem, including its compiled show format and optional licensed backend services.

https://skybrush.io/[*Skybrush*] is a modular software suite, consisting of the following modules, each of which may be operated on its own or as part of the whole suite:

* Design and validation:
** *Dronetara Studio* - drone show designer framework frontend
** *Skybrush Studio Server* - drone show designer framework backend
** *Skybrush Viewer* - 3D drone show visualiser for testing and presentation purposes
* Execution:
** *Skybrush Live* - drone show management and fleet control framework frontend
** *Skybrush Sidekick* - companion app to *Skybrush Live* that operates an independent, fallback communication channel
** *Skybrush Server* - drone show management and fleet control framework backend
** *Skybrush firmware* - drone show firmware onboard the drones
* Maintenance:
** *Paplan* - Professional ArduPilot Log Analyzer tool


In this manual our focus is on *Dronetara Studio*, which provides drone show design modules and functions in https://www.blender.org/[Blender], an open-source 3D creation suite.

Use the {project-url}/issues[Dronetara Studio issue tracker] for questions and feedback.
