= Basic setup
:imagesdir: ../assets/images

In this page we will go through some basic setup questions of the *Skybrush Studio Plugin for Blender* to be able to start designing a drone show from scratch as smoothly as possible.


== Units

* Blender space units are treated as meters.
* Blender time units are treated as seconds.
* You can use any convenient framerate you wish, just make sure that it is dividable with the desired output frame rate of your trajectories (e.g., 24 FPS -> 4 FPS or 25 FPS -> 5 FPS).


== Mapping of time

Blender uses relative time and this is preserved in the exported `.skyc` files as well. The actual start time of a drone show will be set up during the execution phase later on in *Skybrush Live*.

TIP: We strongly recommend you to start your frames with 0, not 1. Frame 0 in Blender will be relative time 0 s in the `.skyc` output in all cases, regardless of what frame range you export.


== Coordinate system

Blender uses a relative coordinate system with _X_, _Y_ and _Z_ axes. The real world has directions of North-South, East-West and Up-Down in geodetic coordinates (latitude, longitude, altitude).

The mapping from relative to real coordinates is handled by *Skybrush Live* during the actual setup of your drone show according to the following rules:

1. The origin (0, 0, 0) in Blender will be mapped to a so called _show origin_ in *Skybrush Live*. This can be moved around freely in your geodetic coordinate system on the map or can be set to a specific value you prefer.

2. The _X_, _Y_ and _Z_ axes will be mapped to relative directions of _front_, _left_ and _up_, consecutively, where  _front_ will be called _show orientation_, which can be rotated freely in *Skybrush Live*.

The table below summarizes all mappings between the relative and absolute coordinate system.

[frame=none]
.Mapping between relative and geodetic coordinate systems
|===
|Skybrush Studio Plugin for Blender | Skybrush Live

|(relative coordinates)|(absolute/geodetic coordinates)

| (0, 0, 0) | show origin
| X | front (show orientation)
| Y | left
| Z | up
|===


== Useful Blender settings

We suggest you to check the following Blender settings before you start designing your drone show:

* setup your first frame to 0 (instead of the default 1)
* set your rendering frame rate to a convenient value
* If you use a preview frame range separately from the render frame range, make sure it is enabled, otherwise it will give back (0, 0) values in the Blender API that might result in errorous outputs in certain cases
* in the View tab on the sidebar of the 3D Viewport Editor setup a convenient Clip Start and End value to make your drones visible during the whole show in case you need to render your show
